trigger:
  branches:
    include:
    - main
    - main-internal

pr: none

variables:
- group: 'Paint Dev Variables'

jobs:
- job: Job_1
  displayName: Paint Deployment
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self

  - task: NodeTool@0
    displayName: Use Node 14.17.0
    inputs:
      versionSpec: '14.17.0'

  - task: YarnInstaller@3
    displayName: 'Install Yarn'
    inputs:
      versionSpec: '1.22.5'

  - script: npm install -g npm@7
    displayName: 'Installing npm v7'

  - task: npmAuthenticate@0
    inputs:
      workingFile: '.npmrc'

  - task: Yarn@3
    displayName: 'Yarn Install'
    inputs:
        productionMode: false

  - task: Npm@1
    displayName: Paint Build
    inputs:
      command: 'custom'
      customCommand: 'run build:prod'

  - task: AzureWebApp@1
    displayName: 'Azure Web App Deploy: paint'
    inputs:
      azureSubscription: 'Taos-Apps-Dev-Paint'
      appType: 'webApp'
      appName: 'paint-bot-webapp'
      package: '$(System.DefaultWorkingDirectory)/dist'
      deploymentMethod: 'auto'